apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emt-backend
  namespace: emt-lab
spec:
  rules:
  - host: emt-backend.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emt-backend
            port:
              number: 9090