apiVersion: apps/v1
kind: Deployment
metadata:
  name: emt-backend
  namespace: emt-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emt-backend
  template:
    metadata:
      labels:
        app: emt-backend
    spec:
      containers:
        - name: emt-backend
          image: mihaela19/emt-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev

           
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://emt-db:5432/emt_shop"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
