apiVersion: v1
kind: Service
metadata:
  name: emt-backend-service
  namespace: emt-lab
spec:
  selector:
    app: emt-backend
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
