apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: emt-lab
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://emt-db:5432/emt_shop
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
