apiVersion: apps/v1
kind: Deployment
metadata:
  name: emt-frontend
  namespace: emt-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emt-frontend
  template:
    metadata:
      labels:
        app: emt-frontend
    spec:
      containers:
        - name: emt-frontend
          image: mihaela19/emt-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000